###
GET http://localhost:3000/users
###

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "usuario": "diego",
    "email": "diego.orozco@correo.mx",
    "password": "diego"
}
###

###
POST http://localhost:3000/horario
Content-Type: application/json

{
    "nombre": "Prueba",
    "profesor": "Prueba",
    "creditos": 8,
    "rubros": [{"Practicas": 30}, {"Tareas": 25}, {"Proyecto": 45}],
    "periodo": "Prueba",
    "horario": [{"Martes": 11}, {"Jueves": 11}]
}
###

###
POST http://localhost:3000/tareas 
Content-Type: application/json

{
    "nombre": "Proyecto Final",
    "materia": "Desarrollo de Aplicaciones y Servicios Web",
    "categoria": "Proyecto",
    // fecha de entrega como tipo date
    "fechaEntrega": "2021-05-20",
    "descripcion": "Desarrollar una aplicación web con NodeJS y MongoDB"
}
###

###
GET http://localhost:3000/tareas
###

###
PUT http://localhost:3000/tareas/656818a241a54db3692d65a2
Content-Type: application/json

{
    "nombre": "probando",
    "materia": "probando",
    "categoria": "Proyecto",
    // fecha de entrega como tipo date
    "fechaEntrega": "2021-05-20",
    "descripcion": "probando"
}
###

###
GET http://localhost:3000/tareas/656818a241a54db3692d65a2
###

###
DELETE http://localhost:3000/tareas/656818a241a54db3692d65a2
###