###
GET http://localhost:3000/users
###

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "usuario": "diego",
    "email": "diego.orozco@correo.mx",
    "password": "diego"
}
###

###
POST http://localhost:3000/horario
Content-Type: application/json

{
    "nombre": "Estrategias Algorítmicas",
    "profesor": "Luis Gatica",
    "creditos": 8,
    "rubros": [{"Examenes": 40}, {"Tareas": 60}],
    "periodo": "Primavera 2024",
    "horario": [{"Lunes": 9}, {"Miercoles": 9}]
}
###

###
GET http://localhost:3000/horario
###